<?php
/**
 * Mageinn_AdminExtra extension
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category    Mageinn
 * @package     Mageinn_AdminExtra
 * @copyright   Copyright (c) 2014 Mageinn. (http://mageinn.com/)
 * @license     http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */


/**
 * @category   Mageinn
 * @package    Mageinn_AdminExtra
 * @author     Mageinn
 */
?>
<div class="entry-edit">
    <div class="entry-edit-head">
        <h4 class="icon-head head-edit-form fieldset-legend"><?php echo $this->__('Images'); ?></h4>
        <div class="form-buttons"></div>
    </div>
    <div class="fieldset " id="fields">
        <div class="hor-scroll">
        <table cellspacing="0" class="form-list">
            <tr>
                <td class="label"><label for="base_image"><?php echo $this->__('Base Image'); ?></label></td>
                <td class="value use-default">
                    <input type="checkbox" name="use_default[]" id="image_default" value="image" />
                    <label for="base_image_default" class="normal"><?php echo $this->__('Use Default Value'); ?></label>
                </td>
                <td class="scope-label"><span class="nobr">[<?php echo $this->__('STORE VIEW'); ?>]</span></td>
                <td class="value"></td>
            </tr>
            <tr>
                <td class="label"><label for="small_image"><?php echo $this->__('Small Image'); ?></label></td>
                <td class="value use-default">
                    <input type="checkbox" name="use_default[]" id="small_image_default" value="small_image" />
                    <label for="small_image_default" class="normal"><?php echo $this->__('Use Default Value'); ?></label>
                </td>
                <td class="scope-label"><span class="nobr">[<?php echo $this->__('STORE VIEW'); ?>]</span></td>
                <td class="value"></td>
            </tr>
            <tr>
                <td class="label"><label for="thumbnail"><?php echo $this->__('Thumbnail'); ?></label></td>
                <td class="value use-default">
                    <input type="checkbox" name="use_default[]" id="thumbnail_default" value="thumbnail" />
                    <label for="thumbnail_default" class="normal"><?php echo $this->__('Use Default Value'); ?></label>
                </td>
                <td class="scope-label"><span class="nobr">[<?php echo $this->__('STORE VIEW'); ?>]</span></td>
                <td class="value"></td>
            </tr>
        </table>
        </div>
    </div>
</div>